# https://docs.travis-ci.com/user/deployment/pages/
language: node_js
node_js:
- '6'
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
before_install:
- npm install -g npm
- java -version
- npm -version
- npm install
dist: trusty
