# https://docs.travis-ci.com/user/deployment/pages/
language: node_js
node_js:
- '8'
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
before_script:
- npm update ultimate-comparison
cache:
  directories:
    - node_modules
dist: trusty
