title: Ultimate-Comparison
subtitle: Ultimate tex maker comparison framework
selectTitle: Criteria
tableTitle: Comparison of tex makers
repository: 'https://github.com/ultimate-comparisons/ultimate-latex-makers-comparison.git'
details:
  header:
    nameRef: id
    urlRef: inline
  body:
    title: >-
      Comparison of different tex makers, based on
      <http://www.arakhne.org/autolatex/>.
    bodyRef: description
citation:
  csl: apa.csl
  bib: literature.bib
criteria:
  - id:
      name: Name
      search: false
      table: true
      detail: false
  - description:
      name: Short description
      search: false
      detail: true
      type: markdown
  - Implementation:
      table: false
      search: true
      placeholder: Select implementation ...
      andSearch: false
      type: label
      values:
        Sh:
          backgroundColor: '#EA3711'
        Perl:
          backgroundColor: '#11EAD3'
        Python:
          backgroundColor: '#4F11EA'
        Makefile:
          backgroundColor: '#EA6311'
        csh:
          backgroundColor: '#C6EA11'
        Ruby:
          backgroundColor: '#113FEA'
        Bash:
          backgroundColor: '#77EA11'
        C:
          backgroundColor: '#9811EA'
  - Date:
      table: false
      search: true
      placeholder: Select year ...
      andSearch: false
      rangeSearch: true
      values:
        '1993':
          backgroundColor: '#11EAD3'
        '1997':
          backgroundColor: '#C6EA11'
        '2001':
          backgroundColor: '#9811EA'
        '2003':
          backgroundColor: '#4F11EA'
        '2010':
          backgroundColor: '#77EA11'
        '2012':
          backgroundColor: '#EA6311'
        '2013':
          backgroundColor: '#2BEA11'
        '2014':
          backgroundColor: '#EA3711'
  - Supported Tools:
      table: true
      search: true
      placeholder: Select supported tools ...
      andSearch: true
      type: label
      values:
        latex:
          backgroundColor: '#EA3711'
        pdflatex:
          backgroundColor: '#11EAD3'
        xelatex:
          backgroundColor: '#4F11EA'
        lualatex:
          backgroundColor: '#EA6311'
        bibtex:
          backgroundColor: '#C6EA11'
        biber:
          backgroundColor: '#113FEA'
        makeindex:
          backgroundColor: '#77EA11'
        makeglossaries:
          backgroundColor: '#9811EA'
        dvips:
          backgroundColor: '#2BEA11'
        ps2pdf:
          backgroundColor: '#EA9E11'
        dvipdf:
          backgroundColor: '#11BCEA'
        dvi:
          backgroundColor: '#11EA7A'
        texi2dvi:
          backgroundColor: '#1E11EA'
        etex:
          backgroundColor: '#EAD311'
        aleph:
          backgroundColor: '#8411EA'
        omega:
          backgroundColor: '#BC11EA'
        vtex:
          backgroundColor: '#1187EA'
  - Detect Changes for TeX:
      table: true
      search: true
      placeholder: Select detected changes for tex ...
      andSearch: false
      type: label
      values:
        all:
          backgroundColor: '#EA3711'
        latex:
          backgroundColor: '#11EAD3'
        bibtex:
          backgroundColor: '#4F11EA'
        makeindex:
          backgroundColor: '#EA6311'
  - Detect Changes for BibTeX:
      table: true
      search: true
      placeholder: Select detected changes for bibtex ...
      andSearch: false
      type: label
      values:
        all:
          backgroundColor: '#EA3711'
  - Detect Changes for Images:
      table: true
      search: true
      placeholder: Select detected changes for images ...
      andSearch: false
      type: label
      values:
        all:
          backgroundColor: '#EA3711'
        maybe:
          backgroundColor: '#11EAD3'
  - Automatic File Conversions to PS/PDF/PNG:
      table: true
      search: true
      placeholder: Select automatic conversions to ps/pdf/png ...
      andSearch: true
      type: label
      values:
        asta:
          backgroundColor: '#EA3711'
        dia:
          backgroundColor: '#11EAD3'
        dot:
          backgroundColor: '#4F11EA'
        fig:
          backgroundColor: '#EA6311'
        ggb:
          backgroundColor: '#C6EA11'
        gxl:
          backgroundColor: '#113FEA'
        odg:
          backgroundColor: '#77EA11'
        plot:
          backgroundColor: '#9811EA'
        svg:
          backgroundColor: '#2BEA11'
        vsd:
          backgroundColor: '#EA9E11'
        xmi:
          backgroundColor: '#11BCEA'
  - Automatic File Conversions to TeX:
      table: true
      search: true
      placeholder: Select automatic conversions to tex ...
      andSearch: true
      type: label
      values:
        all:
          backgroundColor: '#EA3711'
        c/c++:
          backgroundColor: '#11EAD3'
        java:
          backgroundColor: '#4F11EA'
        matlab:
          backgroundColor: '#EA6311'
        ml:
          backgroundColor: '#C6EA11'
        perl:
          backgroundColor: '#113FEA'
        python:
          backgroundColor: '#77EA11'
        ruby:
          backgroundColor: '#9811EA'
        sql:
          backgroundColor: '#2BEA11'
        Beamer:
          backgroundColor: '#EA9E11'
  - Automatic File Convertions to PSTeX/PdfTeX:
      table: true
      search: true
      placeholder: Select automatic conversions to pstex/pdftex ...
      andSearch: true
      type: label
      values:
        fig:
          backgroundColor: '#EA3711'
        plot:
          backgroundColor: '#11EAD3'
        dia:
          backgroundColor: '#4F11EA'
        svg:
          backgroundColor: '#EA6311'
        Beamer:
          backgroundColor: '#C6EA11'
  - Export to Elsevier:
      table: true
      search: true
      placeholder: Select support for elsevier ...
      andSearch: false
      type: label
      values:
        'Yes':
          class: label-success
        'No':
          class: label-danger
  - Editor Plugins:
      table: true
      search: true
      placeholder: Select editor plugins ...
      andSearch: false
      type: label
      values:
        Gedit3:
          backgroundColor: '#EA3711'
        Gtk3:
          backgroundColor: '#11EAD3'
        Sublime Text 3:
          backgroundColor: '#4F11EA'
        Gedit2:
          description: deprecated
          backgroundColor: '#EA6311'
        Gtk2:
          description: deprecated
          backgroundColor: '#C6EA11'
        Sublime Text 2:
          description: deprecated
          backgroundColor: '#113FEA'
autoCriteria:
  Implementation:
    values:
      Java: {}
  Supported Tools:
    values:
      luatex: {}
      frontespizio: {}
      latexmk: {}
      synctex: {}
      metapost: {}
      metafont: {}
      gnuplot: {}
      sagetex: {}
      tikzext: {}
  Detect change for TeX:
    search: true
    table: true
    detail: true
    type: label
    values:
      all: {}
      latex: {}
      bibtex: {}
      makeindex: {}
  Detect changes for BibTeX:
    search: true
    table: true
    detail: true
    type: label
    values:
      all: {}
  Detect changes for images:
    search: true
    table: true
    detail: true
    type: label
    values:
      all: {}
      maybe: {}
  Export to Elsevier:
    values:
      'no': {}
  Implementation Language:
    search: true
    table: true
    detail: true
    type: label
    values:
      Bash: {}
      C: {}
      Python: {}
      Ruby: {}
  Automatic File Conversions to PSTeX/PdfTeX:
    search: true
    table: true
    detail: true
    type: label
    values:
      fig: {}
      plot: {}
      dia: {}
      svg: {}
      Beamer: {}
  Date:
    values:
      '"Year"': {}
  Editor Plugins:
    values:
      Gedit 2: {}
      Gtk 2: {}
autoColor:
  License:
    MIT:
      color: '#0d0d0d'
      backgroundColor: 'hsl(210, 100%, 70%)'
    MPL-2.0:
      color: '#ffff00'
      backgroundColor: 'hsl(240, 100%, 70%)'
  Uncolored:
    Color 1:
      color: '#ffff00'
      backgroundColor: 'hsl(270, 100%, 70%)'
    Color 2:
      color: '#0d0d0d'
      backgroundColor: 'hsl(300, 100%, 70%)'
    Color 3:
      color: '#0d0d0d'
      backgroundColor: 'hsl(330, 100%, 70%)'
    Color 4:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
  NumberColumn:
    '100':
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    '199':
      color: '#0d0d0d'
      backgroundColor: 'hsl(30, 100%, 70%)'
    '200':
      color: '#0d0d0d'
      backgroundColor: 'hsl(60, 100%, 70%)'
    '233':
      color: '#0d0d0d'
      backgroundColor: 'hsl(210, 100%, 70%)'
    '250':
      color: '#0d0d0d'
      backgroundColor: 'hsl(90, 100%, 70%)'
    '300':
      color: '#0d0d0d'
      backgroundColor: 'hsl(120, 100%, 70%)'
  Implementation:
    Java:
      color: '#0d0d0d'
      backgroundColor: 'hsl(30, 100%, 70%)'
  Supported Tools:
    frontespizio:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    gnuplot:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    latexmk:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    luatex:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    metafont:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    metapost:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    sagetex:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    synctex:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
    tikzext:
      color: '#0d0d0d'
      backgroundColor: 'hsl(45, 100%, 70%)'
  Detect change for TeX:
    all:
      color: '#0d0d0d'
      backgroundColor: 'hsl(60, 100%, 70%)'
    bibtex:
      color: '#0d0d0d'
      backgroundColor: 'hsl(60, 100%, 70%)'
    latex:
      color: '#0d0d0d'
      backgroundColor: 'hsl(60, 100%, 70%)'
    makeindex:
      color: '#0d0d0d'
      backgroundColor: 'hsl(60, 100%, 70%)'
  Detect changes for BibTeX:
    all:
      color: '#0d0d0d'
      backgroundColor: 'hsl(75, 100%, 70%)'
  Detect changes for images:
    all:
      color: '#0d0d0d'
      backgroundColor: 'hsl(90, 100%, 70%)'
    maybe:
      color: '#0d0d0d'
      backgroundColor: 'hsl(90, 100%, 70%)'
  Automatic File Convertions to PS/PDF/PNG:
    asta:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    dia:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    dot:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    fig:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    ggb:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    gxl:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    odg:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    plot:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    svg:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    vsd:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
    xmi:
      color: '#0d0d0d'
      backgroundColor: 'hsl(105, 100%, 70%)'
  Export to Elsevier:
    'no':
      color: '#0d0d0d'
      backgroundColor: 'hsl(120, 100%, 70%)'
  Implementation Language:
    Bash:
      color: '#0d0d0d'
      backgroundColor: 'hsl(135, 100%, 70%)'
    C:
      color: '#0d0d0d'
      backgroundColor: 'hsl(135, 100%, 70%)'
    Python:
      color: '#0d0d0d'
      backgroundColor: 'hsl(135, 100%, 70%)'
    Ruby:
      color: '#0d0d0d'
      backgroundColor: 'hsl(135, 100%, 70%)'
  Automatic File Convertions to TeX:
    all:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    Beamer:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    c/c++:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    java:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    matlab:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    ml:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    perl:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    python:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    ruby:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
    sql:
      color: '#0d0d0d'
      backgroundColor: 'hsl(150, 100%, 70%)'
  Date:
    '"Year"':
      color: '#0d0d0d'
      backgroundColor: 'hsl(165, 100%, 70%)'
  Automatic File Conversions to PSTeX/PdfTeX:
    Beamer:
      color: '#0d0d0d'
      backgroundColor: 'hsl(180, 100%, 70%)'
    dia:
      color: '#0d0d0d'
      backgroundColor: 'hsl(180, 100%, 70%)'
    fig:
      color: '#0d0d0d'
      backgroundColor: 'hsl(180, 100%, 70%)'
    plot:
      color: '#0d0d0d'
      backgroundColor: 'hsl(180, 100%, 70%)'
    svg:
      color: '#0d0d0d'
      backgroundColor: 'hsl(180, 100%, 70%)'
  Editor Plugins:
    Gedit 2:
      color: '#0d0d0d'
      backgroundColor: 'hsl(195, 100%, 70%)'
    Gtk 2:
      color: '#0d0d0d'
      backgroundColor: 'hsl(195, 100%, 70%)'
autoCitation: {}
